[project]
name = "ufc-pred-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dmytro", email = "160007689+strait593@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "gender-guesser>=0.4.0",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
ufc-pred-model = "ufc_pred_model:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
